// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmcv6t79SQtUcOFfi5WgsN3bNhvHBF4vA',
    appId: '1:97430636970:web:1651feadfb97c74622c3d3',
    messagingSenderId: '97430636970',
    projectId: 'e-store-apple',
    authDomain: 'e-store-apple.firebaseapp.com',
    storageBucket: 'e-store-apple.firebasestorage.app',
    measurementId: 'G-ZCDK0VPF3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWPlxwLy0fuiOXjB_kMXknjKYtEC5piWc',
    appId: '1:97430636970:android:b204ea1c0adacc8d22c3d3',
    messagingSenderId: '97430636970',
    projectId: 'e-store-apple',
    storageBucket: 'e-store-apple.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoCqje8cR9gBCN5uuz3P3fzaTPZfYvsLs',
    appId: '1:97430636970:ios:af7e71fef443e3bd22c3d3',
    messagingSenderId: '97430636970',
    projectId: 'e-store-apple',
    storageBucket: 'e-store-apple.firebasestorage.app',
    iosBundleId: 'com.example.eStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoCqje8cR9gBCN5uuz3P3fzaTPZfYvsLs',
    appId: '1:97430636970:ios:af7e71fef443e3bd22c3d3',
    messagingSenderId: '97430636970',
    projectId: 'e-store-apple',
    storageBucket: 'e-store-apple.firebasestorage.app',
    iosBundleId: 'com.example.eStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmcv6t79SQtUcOFfi5WgsN3bNhvHBF4vA',
    appId: '1:97430636970:web:7f2133ceb35ee91322c3d3',
    messagingSenderId: '97430636970',
    projectId: 'e-store-apple',
    authDomain: 'e-store-apple.firebaseapp.com',
    storageBucket: 'e-store-apple.firebasestorage.app',
    measurementId: 'G-3H7EKGS3WS',
  );
}
